// Dump the composite (struct/union) data types Ghidra's XbeLoader recognized —
// XBE_FILE_HEADER, XBE_CERTIFICATE_HEADER, XBE_SECTION_HEADER, ... — as
// byte-exact C typedefs, written to a file. Invoked headlessly via:
//   analyzeHeadless ... -process <program> -noanalysis \
//       -scriptPath <ghidra_scripts_dir> \
//       -postScript DumpStructs.java /path/to/structs.h
//
// Layout fidelity matters: a harvested struct must reproduce the original
// member offsets so `.CertificateHeader + 8`-style access resolves to the same
// baked disp32 the matched object carries. We therefore wrap every record in
// #pragma pack(1), emit one field per Ghidra component (gaps included), and
// size every field we don't recognize as a scalar from its *component* length
// (Ghidra's dynamic string types lie about DataType.getLength()).
//
// Scope: only the program-local archive is dumped, so Ghidra's bundled glibc
// types (_IO_FILE, sockaddr, ...) are filtered out; empty placeholders are
// skipped. Composites are emitted dependency-first so a by-value member never
// references an undeclared type.
//
// @category iVCS

import ghidra.app.script.GhidraScript;
import ghidra.program.model.data.Array;
import ghidra.program.model.data.Composite;
import ghidra.program.model.data.DataType;
import ghidra.program.model.data.DataTypeComponent;
import ghidra.program.model.data.DataTypeManager;
import ghidra.program.model.data.Pointer;
import ghidra.program.model.data.SourceArchive;
import ghidra.program.model.data.Union;

import java.io.FileWriter;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

public class DumpStructs extends GhidraScript {

    // Ghidra primitive type name -> a scalar MSVC 7.1 (/TC, C89) accepts.
    // Names already valid C pass through as identities; lowercase Ghidra
    // aliases and 64-bit forms are remapped. `undefined*` is handled
    // separately; anything else falls back to a component-sized byte run.
    private static final Map<String, String> PRIMITIVES = new HashMap<>();
    static {
        PRIMITIVES.put("char", "char");
        PRIMITIVES.put("short", "short");
        PRIMITIVES.put("int", "int");
        PRIMITIVES.put("long", "long");
        PRIMITIVES.put("float", "float");
        PRIMITIVES.put("double", "double");
        PRIMITIVES.put("void", "void");
        PRIMITIVES.put("byte", "unsigned char");
        PRIMITIVES.put("sbyte", "signed char");
        PRIMITIVES.put("uchar", "unsigned char");
        PRIMITIVES.put("bool", "unsigned char");
        PRIMITIVES.put("word", "unsigned short");
        PRIMITIVES.put("ushort", "unsigned short");
        PRIMITIVES.put("wchar_t", "unsigned short");
        PRIMITIVES.put("wchar16", "unsigned short");
        PRIMITIVES.put("uint", "unsigned int");
        PRIMITIVES.put("dword", "unsigned long");
        PRIMITIVES.put("ulong", "unsigned long");
        PRIMITIVES.put("qword", "unsigned __int64");
        PRIMITIVES.put("ulonglong", "unsigned __int64");
        PRIMITIVES.put("longlong", "__int64");
        PRIMITIVES.put("code", "void");
    }

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length != 1) {
            throw new RuntimeException("expected 1 arg (out_path); got " + args.length);
        }
        String outPath = args[0];

        DataTypeManager dtm = currentProgram.getDataTypeManager();
        SourceArchive local = dtm.getLocalSourceArchive();

        // Collect program-local, non-empty composites keyed by their sanitized
        // C name so by-value member references and the typedef we emit agree.
        Map<String, Composite> composites = new LinkedHashMap<>();
        Iterator<DataType> all = dtm.getAllDataTypes();
        while (all.hasNext()) {
            DataType dt = all.next();
            if (!(dt instanceof Composite)) {
                continue;
            }
            Composite c = (Composite) dt;
            if (c.getNumComponents() == 0) {
                continue;  // empty placeholder — not legal C, no layout to harvest
            }
            if (!dt.getSourceArchive().getSourceArchiveID().equals(local.getSourceArchiveID())) {
                continue;  // bundled glibc / generic types, not loader-recognized
            }
            composites.put(sanitize(dt.getName()), c);
        }

        StringBuilder sb = new StringBuilder();
        sb.append("/* Auto-generated by DumpStructs.java from Ghidra's XbeLoader symbol DB. */\n");
        sb.append("/* ").append(composites.size()).append(" composite type(s). */\n");
        sb.append("#pragma pack(push, 1)\n\n");

        Set<String> names = composites.keySet();
        Set<String> done = new HashSet<>();
        Set<String> stack = new HashSet<>();
        for (Composite c : composites.values()) {
            emit(c, composites, names, done, stack, sb);
        }

        sb.append("#pragma pack(pop)\n");

        try (FileWriter w = new FileWriter(outPath)) {
            w.write(sb.toString());
        }
    }

    // Post-order emit: declare every by-value dependency before the composite
    // that contains it. `stack` breaks pathological cycles (impossible by value
    // in valid C, but Ghidra data can be malformed).
    private void emit(
            Composite c,
            Map<String, Composite> all,
            Set<String> names,
            Set<String> done,
            Set<String> stack,
            StringBuilder sb) {
        String name = sanitize(c.getName());
        if (done.contains(name) || stack.contains(name)) {
            return;
        }
        stack.add(name);
        for (DataTypeComponent comp : c.getComponents()) {
            DataType base = baseValueType(comp.getDataType());
            if (base instanceof Composite) {
                Composite dep = all.get(sanitize(base.getName()));
                if (dep != null) {
                    emit(dep, all, names, done, stack, sb);
                }
            }
        }
        stack.remove(name);
        sb.append(renderComposite(c, name, names));
        done.add(name);
    }

    private String renderComposite(Composite c, String name, Set<String> names) {
        boolean isUnion = c instanceof Union;
        StringBuilder s = new StringBuilder();
        s.append("typedef ").append(isUnion ? "union" : "struct").append(" {\n");
        for (DataTypeComponent comp : c.getComponents()) {
            String field = comp.getFieldName();
            if (field == null || field.isEmpty()) {
                field = String.format("field_0x%x", comp.getOffset());
            }
            s.append("\t")
                .append(renderType(comp.getDataType(), sanitize(field), names, comp.getLength()))
                .append(String.format(";  /* +0x%x */\n", comp.getOffset()));
        }
        s.append("} ").append(name).append(";\n\n");
        return s.toString();
    }

    // Render `<type> <decorated-name>` for one field. Arrays recurse, pushing
    // the dimension onto the name; pointers collapse to `unsigned char *`
    // (the slot stays 4 bytes and matching never needs the pointee, while the
    // byte-pointer type keeps Ghidra's `field + N` arithmetic legal under
    // MSVC — `void *` arithmetic is an error); `undefined*` and
    // any unrecognized type become a byte run sized to preserve the exact
    // footprint — `fallbackBytes` is the component length, which is the only
    // trustworthy size for Ghidra's dynamic string types.
    private String renderType(DataType dt, String name, Set<String> names, int fallbackBytes) {
        if (dt instanceof Array) {
            Array arr = (Array) dt;
            DataType elem = arr.getDataType();
            return renderType(elem, name + "[" + arr.getNumElements() + "]", names, elem.getLength());
        }
        if (dt instanceof Pointer) {
            return "unsigned char *" + name;
        }
        String tn = dt.getName();
        if (tn.startsWith("undefined")) {
            return bytesField(name, dt.getLength());
        }
        if (PRIMITIVES.containsKey(tn)) {
            return PRIMITIVES.get(tn) + " " + name;
        }
        if (dt instanceof Composite && names.contains(sanitize(tn))) {
            return sanitize(tn) + " " + name;
        }
        return bytesField(name, fallbackBytes > 0 ? fallbackBytes : dt.getLength());
    }

    private String bytesField(String name, int len) {
        return len > 1 ? "unsigned char " + name + "[" + len + "]" : "unsigned char " + name;
    }

    private DataType baseValueType(DataType dt) {
        while (dt instanceof Array) {
            dt = ((Array) dt).getDataType();
        }
        return dt;
    }

    // Map a Ghidra identifier to a legal C identifier: anything outside
    // [A-Za-z0-9_] becomes '_', and a leading digit is prefixed.
    private String sanitize(String raw) {
        StringBuilder s = new StringBuilder(raw.length());
        for (int i = 0; i < raw.length(); i++) {
            char ch = raw.charAt(i);
            s.append(Character.isLetterOrDigit(ch) || ch == '_' ? ch : '_');
        }
        if (s.length() == 0 || Character.isDigit(s.charAt(0))) {
            s.insert(0, '_');
        }
        return s.toString();
    }
}
